# Generated by Django 2.1.2 on 2018-11-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=17, primary_key=True, serialize=False)),
            ],
        ),
    ]
