# Generated by Django 2.1.2 on 2018-11-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_map_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frag',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='frag',
            name='location_x',
        ),
        migrations.RemoveField(
            model_name='frag',
            name='location_y',
        ),
        migrations.RemoveField(
            model_name='frag',
            name='location_z',
        ),
        migrations.AddField(
            model_name='frag',
            name='killer_location_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='frag',
            name='killer_location_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='frag',
            name='killer_location_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='frag',
            name='victim_location_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='frag',
            name='victim_location_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='frag',
            name='victim_location_z',
            field=models.FloatField(default=0.0),
        ),
    ]
