# Generated by Django 2.1.2 on 2018-11-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181031_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='playername',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
