# Generated by Django 2.1.2 on 2018-11-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181031_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='frag',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
    ]
