# Generated by Django 2.1.2 on 2018-11-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181108_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='players',
            field=models.ManyToManyField(to='api.Player'),
        ),
    ]
