# Generated by Django 2.1.2 on 2018-11-20 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_round_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Constructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_index', models.IntegerField()),
                ('round_time', models.IntegerField()),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ConstructionClass')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crc', models.IntegerField(unique=True)),
                ('version', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PawnClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Player')),
            ],
        ),
        migrations.CreateModel(
            name='RallyPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_index', models.IntegerField()),
                ('squad_index', models.IntegerField()),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('location_z', models.FloatField()),
                ('spawn_count', models.IntegerField()),
                ('is_established', models.BooleanField()),
                ('establisher_count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('destroyed_at', models.DateTimeField(null=True)),
                ('destroyed_reason', models.CharField(choices=[('overrun', 'Overrun'), ('exhausted', 'Exhausted'), ('damaged', 'Damaged'), ('deleted', 'Deleted'), ('replaced', 'Replaced'), ('spawn_kill', 'Spawn Kill'), ('abandoned', 'Abandoned'), ('encroached', 'Encroached Upon')], max_length=32, null=True)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='playername',
            name='date',
        ),
        migrations.RemoveField(
            model_name='round',
            name='crc',
        ),
        migrations.RemoveField(
            model_name='round',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='round',
            name='map',
        ),
        migrations.RemoveField(
            model_name='round',
            name='players',
        ),
        migrations.RemoveField(
            model_name='round',
            name='version',
        ),
        migrations.AddField(
            model_name='map',
            name='bounds_ne_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='bounds_ne_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='bounds_sw_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='bounds_sw_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='offset',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='winner',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Map'),
        ),
        migrations.AddField(
            model_name='log',
            name='players',
            field=models.ManyToManyField(to='api.Player'),
        ),
        migrations.AddField(
            model_name='log',
            name='rounds',
            field=models.ManyToManyField(to='api.Round'),
        ),
        migrations.AddField(
            model_name='frag',
            name='killer_pawn_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.PawnClass'),
        ),
        migrations.AddField(
            model_name='frag',
            name='victim_pawn_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.PawnClass'),
        ),
    ]
