# Generated by Django 2.1.2 on 2018-12-09 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20181209_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='rounds',
        ),
        migrations.AddField(
            model_name='round',
            name='log',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Log'),
            preserve_default=False,
        ),
    ]
