# Generated by Django 2.1.2 on 2018-11-01 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_damagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_index', models.SmallIntegerField()),
                ('time', models.IntegerField()),
                ('killer_team_index', models.SmallIntegerField()),
                ('victim_team_index', models.SmallIntegerField()),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('location_z', models.IntegerField()),
                ('distance', models.FloatField()),
                ('damage_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.DamageType')),
                ('killer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Player')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Player')),
            ],
        ),
    ]
