# Generated by Django 2.1.2 on 2018-11-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_playername_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='crc',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='ips',
            field=models.ManyToManyField(to='api.PlayerIP'),
        ),
    ]
