# Generated by Django 2.1.2 on 2018-11-02 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_frag_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='id',
        ),
        migrations.RemoveField(
            model_name='round',
            name='frags',
        ),
        migrations.RemoveField(
            model_name='round',
            name='players',
        ),
        migrations.AddField(
            model_name='frag',
            name='round',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Round'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='round',
            name='map',
        ),
        migrations.AddField(
            model_name='round',
            name='map',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Map'),
            preserve_default=False,
        ),
    ]
