# Generated by Django 2.1.2 on 2018-11-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181120_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rallypoint',
            old_name='player_id',
            new_name='player',
        ),
    ]
