# Generated by Django 2.1.2 on 2018-12-09 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20181209_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_index', models.IntegerField()),
                ('round_time', models.IntegerField()),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('location_z', models.IntegerField()),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ConstructionClass')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='constructions',
            name='classname',
        ),
        migrations.DeleteModel(
            name='Constructions',
        ),
    ]
