# Generated by Django 2.1.2 on 2018-12-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_construction_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='crc',
            field=models.BigIntegerField(unique=True),
        ),
    ]
