# Generated by Django 2.1.2 on 2019-01-17 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20181220_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_time', models.IntegerField()),
                ('team_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Map')),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destroyed_reason', models.CharField(choices=[('lead', 'Lead'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=32)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Player')),
            ],
        ),
        migrations.AddField(
            model_name='capture',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Objective'),
        ),
        migrations.AddField(
            model_name='capture',
            name='players',
            field=models.ManyToManyField(to='api.Player'),
        ),
        migrations.AddField(
            model_name='capture',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Round'),
        ),
    ]
